Add remove_from_shipwire into Spree::Shipment
nebulab/solidus_shipwire pull request #24
Opened 2018-11-27 14:47 UTC by BravoSimone

This method checks if the shipment has a shipire_id and if the cancel is
successfull api action it removes the shipwire_id from the shipment

2018-11-28 21:01 UTC, kennyadsl requested changes

2018-11-28 21:01 UTC, kennyadsl commented on app/models/shipment_decorator.rb
> +    def cancel_from_shipwire
I think it's better to move this into the [API class](https://github.com/nebulab/solidus_shipwire/blob/3e9dc1219c5f9d0a24e2e399a1cb5bf839f472e3/lib/solidus_shipwire/shipwireable/shipwire_api.rb) and follow the style of the rest of the methods there, right?

2018-12-05 16:55 UTC, kennyadsl approved these changes

2018-12-05 17:00 UTC, BravoSimone commented
I'm merging because the build is failing for reasons external to the gem itself. I've rerun the master build and as you can see the same tasks are failing:

1) [Old build](https://travis-ci.org/nebulab/solidus_shipwire/builds/432870109)
2) [New build of the same branch](https://travis-ci.org/nebulab/solidus_shipwire/builds/432913024)

2018-12-05 17:00 UTC, merged