Add button to sync order in shipwire
nebulab/solidus_shipwire pull request #4
Opened 2017-01-27 13:38 UTC by DanielePalombo

Add button to admin to retry/force sync in shipwire

2017-01-27 13:48 UTC, mtylty requested changes

2017-01-27 13:48 UTC, mtylty commented on app/models/shipwire/orders_decorator.rb
> +  def find(id, params = {})
As discussed, why don't you add a comment explaining the problem with the Shipwire gem?

2017-01-27 13:48 UTC, mtylty commented on app/views/spree/admin/orders/shipwire.html.erb
> +        <li><%= event_links %></li>
is this indented too much?

2017-01-27 13:48 UTC, mtylty commented on app/controllers/spree/admin/orders_controller_decorator.rb
> +    def sync_with_shipwire
can this and the `shipwire` action be merged?

2017-01-27 14:07 UTC, kennyadsl requested changes

2017-01-27 14:07 UTC, kennyadsl commented on app/models/shipwire/orders_decorator.rb
> +  def find(id, params = {})
also, we can avoid class_eval in favor of using prepend

2017-01-27 14:07 UTC, kennyadsl commented on config/routes.rb
> +  Spree::Core::Engine.add_routes do
is this `add_routes` needed? I think it works with `routes.draw` and probably `add_routes`  is also deprecated in the latest versions of solidus.

2017-01-27 14:07 UTC, kennyadsl commented on lib/solidus_shipwire/shipwire_objects/order.rb
> +      def shipTo
why this method is camelCase?

2017-01-27 15:21 UTC, DanielePalombo commented on app/models/shipwire/orders_decorator.rb
> +  def find(id, params = {})
My PR was merged from shipwire :trophy:

2017-01-27 15:31 UTC, kennyadsl commented on app/models/order_decorator.rb
> +    ::SolidusShipwire::ShipwireObjects::Order.new(hash['id'], self, hash)
initial `::` are needed?

2017-01-30 08:58 UTC, DanielePalombo commented
Can i merge this PR?

2017-01-30 09:11 UTC, kennyadsl commented on app/models/shipwire/order_decorator.rb
> +Shipwire::Orders.class_eval do
@DanielePalombo why class eval here?

2017-01-30 09:48 UTC, DanielePalombo commented on app/models/shipwire/order_decorator.rb
> +Shipwire::Orders.class_eval do
because was only a fix, and i don't need to use `super` method. However I changed the class_eval in prepend

2017-01-30 11:26 UTC, mtylty approved these changes

2017-01-30 11:27 UTC, merged